config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('Route');
//Router::extensions(['json']);

Router::scope('/', function ($routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'home']);

    //REST API
    $routes->extensions(['json']);
    $routes->resources('Users');

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */


    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `InflectedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'InflectedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'InflectedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('InflectedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Project.php
<?php
/**
 * Created by PhpStorm.
 * User: Leonardo
 * Date: 29/03/2015
 * Time: 23:59
 */

namespace App\Model\Entity;


use Cake\ORM\Entity;

class Project extends Entity{

}

src/Model/Table/ProjectsTable.php
<?php
/**
 * Created by PhpStorm.
 * User: Leonardo
 * Date: 28/03/2015
 * Time: 23:47
 */

namespace App\Model\Table;

use Cake\ORM\Table;
use Cake\Validation\Validator;

class ProjectsTable extends Table
{
    public function initialize(array $config)
    {
        $this->hasOne('Searches');
        $this->belongsTo('Areas');
        $this->belongsTo('Status');
        $this->belongsTo('Campus');
        $this->belongsTo('IntellectualProperties');
        $this->belongsTo('Users');
        $this->hasMany('Members');
    }

    public function validationDefault(Validator $validator)
    {
        return $validator
            ->notEmpty('name', 'A name is required')
            ->notEmpty('area_id', 'A area is required');
    }

}
?>

src/Controller/ProjectsController.php
<?php

namespace App\Controller;

use App\Controller\AppController;
use App\Model\Table\AreasTable;
use Cake\Event\Event;
use Cake\Network\Exception\NotFoundException;

class ProjectsController extends AppController
{

    public $components = array('Paginator');
    public $paginate = array(
            'limit' => 10,            
    );
    
    public function index($status = NULL, $busca = NULL)
    {

        if ($this->request->is('post')) {
            $busca = $this->request->data["busca"];
            $this->set( 'projects', $this->paginate( $this->Projects->find( 'all' )->contain(['Areas', 'Status'])->where(['title LIKE' => '%'. $busca .'%']) ) );
        }
        //BUSCAS POR STATUS DO PROJETO
        else if ($status!=NULL) {
            $this->set( 'projects', $this->paginate( $this->Projects->find( 'all' )->contain(['Areas', 'Status'])->where(['status_id' => $status])->order(['Projects.id' => 'DESC']) )  );
        } else {
            $this->set( 'projects', $this->paginate( $this->Projects->find( 'all' )->contain(['Areas', 'Status'])->order(['Projects.id' => 'DESC']) ) );
        }
    }

    public function status($status)
    {
        $this->set( 'projects', $this->paginate( $this->Projects->find( 'all' )->contain(['Areas', 'Status'])->where(['status_id' => $status]) )  );
    }

    public function noSearch()
    {
        $this->set( 'projects', $this->paginate( $this->Projects->find( 'all' )->contain(['Areas', 'Status'])->where(['status_id' => 4]) )  );
    }

    public function view($id)
    {
        if (!$id) {
            throw new NotFoundException(__('Invalid project'));
        }
        $this->loadModel('Members');
        $this->loadModel('MembersStatus');
        $this->set('members', $this->Members->find('all')->contain(['MembersStatus'])->where(['Members.project_id' => $id]));
        $this->set( 'projects', $projects = $this->paginate( $this->Projects->find( )->contain(['Areas', 'Status', 'Campus', 'IntellectualProperties'])->where(['projects.id' => $id]) ) );

        //GAMBIARRA
        $projeto_id = 0;
        foreach($projects as $project){
            $projeto_id = $project->id;
        }
        $this->loadModel('Searches');
        $buscas =  $this->Searches->find()->contain(['Users'])->where(['Searches.project_id' => $projeto_id]);
        $result = 0;
        foreach ($buscas as $busca) {
            $result = $busca;
        }
        if($result->id){
            $this->set('busca', $result);
        }else{
            $this->set('busca', NULL);
        }

        //$this->set( 'project', $project = $this->Projects->get($id));
    }

    public function add()
    {
        $this->loadModel('Members');
        $this->loadModel('MembersStatus');

        $project = $this->Projects->newEntity();
        $member = $this->Members->newEntity();

        if ($this->request->is('post')) {
            $project = $this->Projects->patchEntity($project, $this->request->data);
            $project->user_id = $this->Auth->user('id');

            if ($this->Projects->save($project)) {
                $this->Flash->success(__('Projeto cadastrado.'));
                return $this->redirect(['controller' => 'Members','action' => 'add', $project->id]);
            }

            $this->Flash->error(__('Unable to add the project.'));

        }

        $this->set('project', $project);
        $this->set('areas', $this->Projects->Areas->find('all'));
        $this->set('campus', $this->Projects->Campus->find('all'));
        $this->set('intellectual_properties', $this->Projects->IntellectualProperties->find('all'));
        $this->set('members_status', $this->MembersStatus->find('all'));
    }

    public function edit($id = NULL)
    {
        $this->loadModel('Members');
        $this->loadModel('MembersStatus');
        $this->set('members', $this->Members->find('all')->contain(['MembersStatus'])->where(['Members.project_id' => $id]));
        $this->set('areas', $this->Projects->Areas->find('all'));
        $this->set('campus', $this->Projects->Campus->find('all'));
        $this->set('intellectual_properties', $this->Projects->IntellectualProperties->find('all'));


        if (!$id) {
            throw new NotFoundException(__('Invalid user'));
        }

        $project = $this->Projects->get($id);
        if ($this->request->is(['post', 'put'])) {
            $this->Projects->patchEntity($project, $this->request->data);
            if ($this->Projects->save($project)) {
                $this->Flash->success(__('Your project has been updated.'));
                return $this->redirect(['action' => 'view', $project->id]);
            }
            $this->Flash->error(__('Unable to update your project.'));
        }

        $this->set('project', $project);
    }

    public function delete($id)
    {
        $project = $this->Projects->get($id);
        if ($this->Projects->delete($project)) {
            $this->Flash->success(__('The project with id: {0} has been deleted.', h($id)));

            //deletar todas as buscas
            $this->loadModel('Searches');
            $searches = $this->Searches->find('all')->where(['project_id'=>$id]);

            foreach($searches as $search){
                $this->Searches->delete($search);
            }

            return $this->redirect(['action' => 'index']);
        }
    }


}
?>

src/Template/Projects/add.ctp
<div class="container">

    <!-- BREADCRUMB -->
    <ol class="breadcrumb">
        <li><?= $this->Html->link('Home', array('controller'=>'Pages', 'action'=>'home')) ?></li>
        <li><?= $this->Html->link('Projetos', array('controller'=>'Projects', 'action'=>'index')) ?></li>
        <li class="active">Cadastrar Projeto</li>
    </ol>

    <!-- CADASTRAR -->
    <ul class="rounded-buttons-title" style="clear:both;margin-top:30px">
        <li>
            <a class="glyphicon glyphicon-plus"></a>
        </li>
        <li>
            <h3>Novo projeto</h3>
        </li>
    </ul>

    <div class="form-signin">
        <?= $this->Form->create($project) ?>        
        <div class="list-group" style="margin-top:30px">
            <div class="list-group-item" style="padding-bottom:10px">
                <label for="title">Título</label><br>
                <?= $this->Form->input(('title'),  array('class'=>'form-control', 'label'=>false)) ?><br>
                <label for="abstract">Resumo</label><br>
                <?= $this->Form->input(('abstract'),  array('class'=>'form-control', 'label'=>false)) ?><br>
                <label for="area_id">Área do conhecimento</label><br>
                <select name="area_id">
                <?php
                    foreach($areas as $area){
                        echo "<option value=$area->id>$area->name</option>";
                    }
                ?>
                </select><br><br>
                <label for="campus_id">Campus</label><br>
                <select name="campus_id">
                    <?php
                    foreach($campus as $camp){
                        echo "<option value=$camp->id>$camp->name</option>";
                    }
                    ?>
                </select><br><br>
                <label for="intellectual_property_id">Propriedade intelectual</label><br>
                <select name="intellectual_property_id">
                    <?php
                    foreach($intellectual_properties as $intellectual_property){
                        echo "<option value=$intellectual_property->id>$intellectual_property->name</option>";
                    }
                    ?>
                </select><br><br>
                <hr>
                <?= $this->Form->button(__('Cadastrar'), array('class'=>'btn btn-success', 'id' => 'confirm')); ?>
        </div>
        </div>
        
        <?= $this->Form->end() ?><?= $this->Flash->render() ?>
    </div>
</div>

<script>
    document.getElementById("projetos").className = "ativado";
</script>

src/Template/Projects/edit.ctp
<div class="container">

    <!-- BREADCRUMB -->
    <ol class="breadcrumb">
        <li><?= $this->Html->link('Home', array('controller'=>'Pages', 'action'=>'home')) ?></li>
        <li><?= $this->Html->link('Projetos', array('controller'=>'Projects', 'action'=>'index')) ?></li>
        <li class="active">Editar</li>
    </ol>

    <!-- EDITAR -->
    <ul class="rounded-buttons-title" style="clear:both;margin-top:30px">
        <li>
            <a class="glyphicon glyphicon-pencil"></a>
        </li>
        <li>
            <h3>Editar</h3>
        </li>
    </ul>

    <?= $this->Form->create($project);?>
    <div class="list-group" style="margin-top:30px">
        <div class="list-group-item" style="padding-bottom:10px">         
            <label for="title">Título</label><br>             
            <?= $this->Form->input(('title'),  array('class'=>'form-control', 'label'=>false));?><br>
            <label for="abstract">Resumo</label><br>             
            <?= $this->Form->input(('abstract'),  array('class'=>'form-control', 'label'=>false)) ?><br>        
            <label for="title">Área do conhecimento</label><br>
            <select name="area_id">
            <?php
                foreach($areas as $area){
                    if($area->id == $project->area_id) {
                        echo "<option selected value=$area->id>$area->name</option>";
                    } else {
                        echo "<option value=$area->id>$area->name</option>";
                    }
                }
            ?>
            </select><br><br>
            
            <label for="campus_id">Campus</label><br>
            <select name="campus_id">
                <?php
                    foreach($campus as $camp){
                        if($camp->id == $project->campus_id) {
                            echo "<option selected value=$camp->id>$camp->name</option>";
                        } else {
                            echo "<option value=$camp->id>$camp->name</option>";
                        }
                    }
                ?>
            </select><br><br>
                          
            <label for="intellectual_property_id">Propriedade intelectual</label><br>
            <select name="intellectual_property_id">
                <?php
                    foreach($intellectual_properties as $intellectual_property){
                        if($intellectual_property->id == $project->intellectual_property_id) {
                            echo "<option selected value=$intellectual_property->id>$intellectual_property->name</option>";
                        } else {
                            echo "<option value=$intellectual_property->id>$intellectual_property->name</option>";
                        }
                    }
                ?>
            </select><br><br>
            <?= $this->Form->button(__('Salvar'), array('class'=>'btn btn-success', 'id' => 'confirm'));?>
        </div>
    </div>
    <?= $this->Form->end();?>

    <!-- MEMBERS TITLE -->
    <ul class="rounded-buttons-title" style="clear:both;margin-top:30px">
        <li>
            <a class="glyphicon glyphicon-user"></a>
        </li>
        <li>
            <h3>Membros</h3>
        </li>
    </ul>

    <!-- MEMBERS -->
    <ul class="rounded-buttons" style="clear:both">
            <li><?= $this->Html->link('', ['controller'=>'Members', 'action'=>'add', $project->id, 'edit'], array('class'=>'glyphicon glyphicon-plus', 'title' => 'Novo membro')) ?></li>
        </ul>
    <div class="list-group" style="margin-top:30px">   
            <?php 
                $i = 0;
                foreach($members as $member){
                    $i++;
                    
                    echo "<div class='list-group-item' style='padding-bottom:50px'>";
                    echo "<h3>" . $member->name . " </h3><em>". $member->members_status->status ."</em>";
                    echo "<ul class='rounded-buttons pull-right' style='clear:both'>";
                    echo "<li style='padding-right:5px'>";
                    echo "<a href='mailto:" . $member->email . "?Subject=Sistema de Anterioridade' target='_top' title='Enviar e-mail' class='glyphicon glyphicon-envelope'></a>";
                    echo "</li>";
                    echo "<li style='padding-right:5px'>";
                    echo $this->Html->link('', ['controller'=>'Members', 'action'=>'edit', $member->id], array('class'=>'glyphicon glyphicon-pencil', 'title' => 'Editar membro')) . "</li>";
                    echo "<li>";
                    echo $this->Html->link('', ['controller'=>'Members', 'action'=>'delete', $member->id], array('class'=>'glyphicon glyphicon-trash', 'title' => 'Deletar membro'));
                    echo "</li>";
                    echo "</ul>";
                    echo "</div>";
                }
                if($i == 0) {
                    echo "<div class='list-group-item' style='padding-bottom:50px'>";
                    echo "<h3>Nenhum membro cadastrado</h3>";
                    echo "</div>";
                }
            ?>    
    </div>
    </div>             
    </div>

    

</div>

<script>
    document.getElementById("projetos").className = "ativado";
</script>

src/Template/Projects/index - Copia.ctp
<?php $userL = $this->Session->read('Auth.User');?>
<div class="container">
    <ol class="breadcrumb" style="background-color:white">
        <li><?= $this->Html->link('Home', array('controller'=>'Pages', 'action'=>'home')) ?></li>
        <li class="active">Projetos</li>
    </ol>

    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
        <div class="list-group">
            <?= $this->Html->link('Novo Projeto', ['controller'=>'Projects', 'action'=>'add'], array('class'=>'list-group-item')) ?>
        </div>
    </div>

    <!-- SEARCH INPUT -->
    <div class="input-group">
        <form action="" method="POST">
            <div class="col-lg-6">
                <div class="input-group">
                    <input name="busca" type="text" class="form-control" placeholder="Buscar projeto...">

                    <span class="input-group-btn">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                            <li><?= $this->Html->link('Todos os projetos', ['controller'=>'Projects', 'action'=>'index']) ?></li>
                            <li><?= $this->Html->link('Buscas não inicializadas', ['controller'=>'Projects', 'action'=>'index/4']) ?></li>
                            <li><?= $this->Html->link('Buscas em andamento', ['controller'=>'Projects', 'action'=>'index/1']) ?></li>
                            <li><?= $this->Html->link('Buscas encontradas', ['controller'=>'Projects', 'action'=>'index/2']) ?></li>
                            <li><?= $this->Html->link('Buscas não encontradas', ['controller'=>'Projects', 'action'=>'index/3']) ?></li>
                        </ul>
                        <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                    </span>

                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
        </form>
    </div><!-- /SEARCH -->

    <!--<div class="col-xs-12 col-sm-9">-->

    <div class="posts index">
        <div class="list-group" style="margin-top:50px">
            <div class="list-group-item">
                <h3>Azurite</h3>
            </div>
            <div class="list-group-item">
                <h3>Azurite</h3>
            </div>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th><?= $this->Paginator->sort('name', 'Nome') ?></th>
                <th><?= $this->Paginator->sort('area_id', 'Área do conhecimento') ?></th>
                <th><?= $this->Paginator->sort('status_id', 'Status') ?></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php
            $results = 0;
            foreach($projects as $project): $results++?>
                <tr>
                    <td><?= $this->Html->link($project->title, ['controller'=>'Projects', 'action'=>'view', $project->id]) ?></td>
                    <td><?= $project->area->name?></td>
                    <td><?= $project->status->name ?></td>
                    <?php if ($userL['role'] == 'admin') {
                        if ($project->status_id == 4) {
                         echo "<td title='Encaminhar'>" . $this->Html->link('', ['controller' => 'Searches', 'action' => 'listToDesignate', $project->id], array('class' => 'glyphicon glyphicon-arrow-right')) . "</td>";
                        } else
                            echo "<td></td>";
                    }?>
                    <?php if($project->status_id == 4) {
                        echo "<td title='Começar busca'>" . $this->Html->link('', ['controller' => 'Searches', 'action' => 'add', $project->id], array('class' => 'glyphicon glyphicon-search')) . "</td>";
                    } else {
                        echo "<td></td>";
                    }?>

                    <?php if ($userL['role'] == 'admin') {
                    echo "<td title='Editar'>" . $this->Html->link('', ['controller'=>'Projects', 'action'=>'edit', $project->id], array('class'=>'glyphicon glyphicon-pencil')) . "</td>";
                    }?>
                    <?php if ($userL['role'] == 'admin' || $project->user_id == $userL['id']) {
                        echo "<td title='Deletar'>" . $this->Html->link('', ['controller'=>'Projects', 'action'=>'delete', $project->id], array('class'=>'glyphicon glyphicon-trash')) . "</td>";
                    }?>

                </tr>
            <?php endforeach; if($results == 0)echo "<tr><td><h2>Nenhum projeto encontrado!</h2></td></tr>";?>
            </tbody>
        </table>
    </div>

    <div class="paginator">
        <ul class="pagination">
            <?php
            echo $this->Paginator->prev('< Previous');
            echo $this->Paginator->numbers();
            echo $this->Paginator->next('Next >');
            ?>
        </ul>
    </div>
    <!--</div>-->

</div>

src/Template/Projects/no_search.ctp
<?php $userL = $this->Session->read('Auth.User');?>
<div class="container">
    <h1>Projetos</h1>
    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" style="text-allign:center">
        <div class="list-group">
            <?= $this->Html->link('Novo Projeto', ['controller'=>'Projects', 'action'=>'add'], array('class'=>'list-group-item')) ?>
            <?= $this->Html->link('Projetos sem buscas', ['controller'=>'Projects', 'action'=>'noSearch'], array('class'=>'list-group-item active')) ?>
        </div>
    </div>
    <div class="col-xs-12 col-sm-9">

        <?php //$this->Html->link('Novo projeto', ['controller'=>'Projects', 'action'=>'add'], array('class'=>'glyphicon glyphicon-plus')) ?>
        <div class="posts index">
            <table class="table">
                <thead>
                <tr>
                    <th><?= $this->Paginator->sort('id') ?></th>
                    <th><?= $this->Paginator->sort('name') ?></th>
                    <th><?= $this->Paginator->sort('area_id') ?></th>
                    <th><?= $this->Paginator->sort('Status') ?></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($projects as $project): ?>
                    <tr>
                        <td><?= $project->id ?></td>
                        <td><?= $this->Html->link($project->title, ['controller'=>'Projects', 'action'=>'view', $project->id]) ?></td>
                        <td><?= $project->area->name?></td>
                        <td><?= $project->status->name ?></td>
                        <?php if ($userL['role'] == 'admin') {
                            echo "<td title='Encaminhar'>" . $this->Html->link('', ['controller'=>'Searches', 'action'=>'listToDesignate', $project->id], array('class'=>'glyphicon glyphicon-arrow-right')) . "</td>";
                        }?>
                        <td title="Começar busca"><?= $this->Html->link('', ['controller'=>'Searches', 'action'=>'add', $project->id], array('class'=>'glyphicon glyphicon-search')) ?></td>
                        <?php if ($userL['role'] == 'admin') {
                            echo "<td title='Editar'>" . $this->Html->link('', ['controller'=>'Projects', 'action'=>'edit', $project->id], array('class'=>'glyphicon glyphicon-pencil')) . "</td>";
                        }?>
                        <?php if ($userL['role'] == 'admin' || $project->user_id == $userL['id']) {
                            echo "<td title='Deletar'>" . $this->Html->link('', ['controller'=>'Projects', 'action'=>'delete', $project->id], array('class'=>'glyphicon glyphicon-trash')) . "</td>";
                        }?>

                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <div class="paginator">
            <ul class="pagination">
                <?php
                echo $this->Paginator->prev('< Previous');
                echo $this->Paginator->numbers();
                echo $this->Paginator->next('Next >');
                ?>
            </ul>
        </div>
    </div>
</div>

src/Template/Projects/view.ctp
<?php $userL = $this->Session->read('Auth.User');?>
<div class="container">

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <li><?= $this->Html->link('Home', array('controller'=>'Pages', 'action'=>'home')) ?></li>
        <li><?= $this->Html->link('Projetos', array('controller'=>'Projects', 'action'=>'index')) ?></li>
        <li class="active">Detalhes</li>
    </ol>
    
    
    <?php foreach($projects as $project):?>
      <span class="pull-right" style="color:#777777">Cadastrado em <?php echo $project->created = date("d/m/Y");?></span>
    <!-- BUTTONS -->
    <ul class="rounded-buttons" style="clear:both">
        <?php 
            if ($userL['role'] == 'admin' || $userL['id'] == $project->user_id) :
        ?>
            <li><?=$this->Html->link('', ['controller'=>'Projects', 'action'=>'edit', $project->id], array('class'=>'glyphicon glyphicon-pencil', 'title' => 'Editar projeto'))?></li>                 
        <?php 
            endif 
        ?>
        <?php
            if($busca != NULL) {
                if ($userL['role'] == 'admin' || $userL['id'] == $busca->user_id) {
                    echo "<li>" . $this->Html->link('', ['controller' => 'Searches', 'action' => 'edit', $busca->id], array('class' => 'glyphicon glyphicon-search', 'title' => 'Editar busca')) . "</li>";                                  
                }
            }
        ?> 
    </ul>

    <!-- MAIN -->
    <div class="list-group" style="margin-top:30px">
        <div class="list-group-item" style="padding-bottom:10px">
            <?php
                $cor = ['', 'info', 'danger', 'success', 'warning'];
            ?>
            <span class="label label-<?=$cor[$project->status->id]?> pull-right"><?=$project->status->name?></span>
            <h2><?= $project->title ?></h2>
            <p><em><?= $project->area->name?></em></p><hr>
            <div class="col-md-9" style="overflow:hidden;float:none">
            <div class="col-sm-4" style="text-allign:left">
                <span class="glyphicon glyphicon-map-marker"></span>Campus
                <p><h4><?=$project->campus->name?></h4></p>
            </div>
            <div class="col-sm-4" style="text-allign:left">
                <span class="glyphicon glyphicon-barcode"></span> Propriedade intelectual
                <p><h4><?=$project->intellectual_property->name?></h4></p>
            </div>
            </div>

            <!-- AVALIADOR -->
            <?php 
                if($busca != NULL):?> <hr style="clear:both">
                Avaliador:
                    <blockquote ><em>         
                        <p><?=$busca->user->name?> <!--<a href="mailto:$busca->user->email?Subject=Sistema de Anterioridade" target="_top" title="Enviar e-mail" class="glyphicon glyphicon-envelope"></a>--></p></em></blockquote> 
            <?php 
                endif 
            ?>  
                                            
        </div>
    </div><!-- /MAIN -->

    <?php endforeach ?>

    <!-- RESUMO -->
    <ul class="rounded-buttons-title" style="clear:both;margin-top:30px">
        <li>
            <a class="glyphicon glyphicon-edit"></a>
        </li>
        <li>
            <h3>Resumo</h3>
        </li>
    </ul>

    <div class="list-group" style="margin-top:30px;">
        <div class="list-group-item" style="padding-bottom:30px">
            <p align="justify"><?= nl2br($project->abstract) ?></p>
        </div>
    </div>

    <!-- MEMBERS -->
    <ul class="rounded-buttons-title" style="clear:both;margin-top:30px">
        <li>
            <a class="glyphicon glyphicon-user"></a>
        </li>
        <li>
            <h3>Membros</h3>
        </li>
    </ul>
    
    <div class="list-group" style="margin-top:30px">    
            <?php
                    $member_all = "";
                    $i = 0;
                    foreach($members as $member){                        
                        $i++;
                        echo "<div class='list-group-item' style='padding-bottom:50px'><h3>$member->name</h3></td><td><em>". $member->members_status->status ."<em><ul class='rounded-buttons pull-right' style='clear:both'><li><a href='mailto:$member->email?Subject=Sistema de Anterioridade' target='_top' title='Enviar e-mail' class='glyphicon glyphicon-envelope', 'title' => 'Enviar email'></a></li></div>";
                    } 
                    if($i == 0) {
                        echo "<div class='list-group-item' style='padding-bottom:50px'><h3>Nenhum membro cadastrado</h3></div>";
                    }
                    ?>     
        </div>
    </div>

</div>

<script>
    document.getElementById("projetos").className = "ativado";
</script>